/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as VirgoolRouteImport } from './routes/virgool'
import { Route as GithubRouteImport } from './routes/github'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AparatRouteImport } from './routes/aparat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YoutubeIdRouteImport } from './routes/youtube_.$id'
import { Route as GithubRepoRouteImport } from './routes/github_.$repo'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const VirgoolRoute = VirgoolRouteImport.update({
  id: '/virgool',
  path: '/virgool',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AparatRoute = AparatRouteImport.update({
  id: '/aparat',
  path: '/aparat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeIdRoute = YoutubeIdRouteImport.update({
  id: '/youtube_/$id',
  path: '/youtube/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRepoRoute = GithubRepoRouteImport.update({
  id: '/github_/$repo',
  path: '/github/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aparat': typeof AparatRoute
  '/blogs': typeof BlogsRoute
  '/experience': typeof ExperienceRoute
  '/github': typeof GithubRoute
  '/virgool': typeof VirgoolRoute
  '/youtube': typeof YoutubeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/github/$repo': typeof GithubRepoRoute
  '/youtube/$id': typeof YoutubeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aparat': typeof AparatRoute
  '/blogs': typeof BlogsRoute
  '/experience': typeof ExperienceRoute
  '/github': typeof GithubRoute
  '/virgool': typeof VirgoolRoute
  '/youtube': typeof YoutubeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/github/$repo': typeof GithubRepoRoute
  '/youtube/$id': typeof YoutubeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aparat': typeof AparatRoute
  '/blogs': typeof BlogsRoute
  '/experience': typeof ExperienceRoute
  '/github': typeof GithubRoute
  '/virgool': typeof VirgoolRoute
  '/youtube': typeof YoutubeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/github_/$repo': typeof GithubRepoRoute
  '/youtube_/$id': typeof YoutubeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aparat'
    | '/blogs'
    | '/experience'
    | '/github'
    | '/virgool'
    | '/youtube'
    | '/blog/$slug'
    | '/github/$repo'
    | '/youtube/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aparat'
    | '/blogs'
    | '/experience'
    | '/github'
    | '/virgool'
    | '/youtube'
    | '/blog/$slug'
    | '/github/$repo'
    | '/youtube/$id'
  id:
    | '__root__'
    | '/'
    | '/aparat'
    | '/blogs'
    | '/experience'
    | '/github'
    | '/virgool'
    | '/youtube'
    | '/blog/$slug'
    | '/github_/$repo'
    | '/youtube_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AparatRoute: typeof AparatRoute
  BlogsRoute: typeof BlogsRoute
  ExperienceRoute: typeof ExperienceRoute
  GithubRoute: typeof GithubRoute
  VirgoolRoute: typeof VirgoolRoute
  YoutubeRoute: typeof YoutubeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GithubRepoRoute: typeof GithubRepoRoute
  YoutubeIdRoute: typeof YoutubeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/virgool': {
      id: '/virgool'
      path: '/virgool'
      fullPath: '/virgool'
      preLoaderRoute: typeof VirgoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aparat': {
      id: '/aparat'
      path: '/aparat'
      fullPath: '/aparat'
      preLoaderRoute: typeof AparatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube_/$id': {
      id: '/youtube_/$id'
      path: '/youtube/$id'
      fullPath: '/youtube/$id'
      preLoaderRoute: typeof YoutubeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github_/$repo': {
      id: '/github_/$repo'
      path: '/github/$repo'
      fullPath: '/github/$repo'
      preLoaderRoute: typeof GithubRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AparatRoute: AparatRoute,
  BlogsRoute: BlogsRoute,
  ExperienceRoute: ExperienceRoute,
  GithubRoute: GithubRoute,
  VirgoolRoute: VirgoolRoute,
  YoutubeRoute: YoutubeRoute,
  BlogSlugRoute: BlogSlugRoute,
  GithubRepoRoute: GithubRepoRoute,
  YoutubeIdRoute: YoutubeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
